CREATE TYPE "public"."exercise_category" AS ENUM('squat', 'bench', 'deadlift', 'chest', 'back', 'shoulders', 'legs', 'arms', 'core');--> statement-breakpoint
CREATE TYPE "public"."exercise_equipment" AS ENUM('barbell', 'dumbbell', 'machine', 'cable', 'bodyweight');--> statement-breakpoint
CREATE TYPE "public"."exercise_primary_muscle" AS ENUM('chest', 'back', 'lats', 'shoulders', 'biceps', 'triceps', 'quads', 'hamstrings', 'glutes', 'calves', 'core');--> statement-breakpoint
CREATE TABLE "exercises" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"category" "exercise_category" NOT NULL,
	"equipment" "exercise_equipment" NOT NULL,
	"primary_muscle" "exercise_primary_muscle" NOT NULL,
	CONSTRAINT "exercises_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
INSERT INTO "exercises" ("slug", "name", "category", "equipment", "primary_muscle") VALUES
	('back-squat', 'Back Squat', 'squat', 'barbell', 'quads'),
	('front-squat', 'Front Squat', 'squat', 'barbell', 'quads'),
	('pause-squat', 'Pause Squat', 'squat', 'barbell', 'quads'),
	('box-squat', 'Box Squat', 'squat', 'barbell', 'quads'),
	('bench-press', 'Barbell Bench Press', 'bench', 'barbell', 'chest'),
	('close-grip-bench-press', 'Close-Grip Bench Press', 'bench', 'barbell', 'triceps'),
	('incline-bench-press', 'Incline Barbell Bench Press', 'bench', 'barbell', 'chest'),
	('pause-bench-press', 'Pause Bench Press', 'bench', 'barbell', 'chest'),
	('conventional-deadlift', 'Conventional Deadlift', 'deadlift', 'barbell', 'back'),
	('sumo-deadlift', 'Sumo Deadlift', 'deadlift', 'barbell', 'glutes'),
	('romanian-deadlift', 'Romanian Deadlift', 'deadlift', 'barbell', 'hamstrings'),
	('deficit-deadlift', 'Deficit Deadlift', 'deadlift', 'barbell', 'back'),
	('block-pull', 'Block Pull', 'deadlift', 'barbell', 'back'),
	('dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', 'dumbbell', 'chest'),
	('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', 'dumbbell', 'chest'),
	('dip', 'Dip', 'chest', 'bodyweight', 'chest'),
	('cable-fly', 'Cable Fly', 'chest', 'cable', 'chest'),
	('push-up', 'Push-Up', 'chest', 'bodyweight', 'chest'),
	('barbell-row', 'Barbell Row', 'back', 'barbell', 'back'),
	('pendlay-row', 'Pendlay Row', 'back', 'barbell', 'back'),
	('pull-up', 'Pull-Up', 'back', 'bodyweight', 'lats'),
	('chin-up', 'Chin-Up', 'back', 'bodyweight', 'lats'),
	('lat-pulldown', 'Lat Pulldown', 'back', 'cable', 'lats'),
	('seated-cable-row', 'Seated Cable Row', 'back', 'cable', 'back'),
	('dumbbell-row', 'Dumbbell Row', 'back', 'dumbbell', 'back'),
	('face-pull', 'Face Pull', 'back', 'cable', 'shoulders'),
	('good-morning', 'Good Morning', 'back', 'barbell', 'hamstrings'),
	('overhead-press', 'Overhead Press', 'shoulders', 'barbell', 'shoulders'),
	('push-press', 'Push Press', 'shoulders', 'barbell', 'shoulders'),
	('seated-dumbbell-press', 'Seated Dumbbell Shoulder Press', 'shoulders', 'dumbbell', 'shoulders'),
	('lateral-raise', 'Lateral Raise', 'shoulders', 'dumbbell', 'shoulders'),
	('rear-delt-fly', 'Rear Delt Fly', 'shoulders', 'dumbbell', 'shoulders'),
	('hack-squat', 'Hack Squat', 'legs', 'machine', 'quads'),
	('leg-press', 'Leg Press', 'legs', 'machine', 'quads'),
	('bulgarian-split-squat', 'Bulgarian Split Squat', 'legs', 'dumbbell', 'quads'),
	('leg-extension', 'Leg Extension', 'legs', 'machine', 'quads'),
	('lying-leg-curl', 'Lying Leg Curl', 'legs', 'machine', 'hamstrings'),
	('walking-lunge', 'Walking Lunge', 'legs', 'dumbbell', 'quads'),
	('standing-calf-raise', 'Standing Calf Raise', 'legs', 'machine', 'calves'),
	('barbell-curl', 'Barbell Curl', 'arms', 'barbell', 'biceps'),
	('dumbbell-curl', 'Dumbbell Curl', 'arms', 'dumbbell', 'biceps'),
	('hammer-curl', 'Hammer Curl', 'arms', 'dumbbell', 'biceps'),
	('triceps-pushdown', 'Triceps Pushdown', 'arms', 'cable', 'triceps'),
	('skullcrusher', 'Skullcrusher', 'arms', 'barbell', 'triceps'),
	('overhead-triceps-extension', 'Overhead Triceps Extension', 'arms', 'dumbbell', 'triceps'),
	('plank', 'Plank', 'core', 'bodyweight', 'core'),
	('hanging-leg-raise', 'Hanging Leg Raise', 'core', 'bodyweight', 'core'),
	('cable-crunch', 'Cable Crunch', 'core', 'cable', 'core'),
	('ab-wheel-rollout', 'Ab Wheel Rollout', 'core', 'bodyweight', 'core')
ON CONFLICT ("slug") DO NOTHING;
