-- Data-only migration: Spanish (locale 'es') display names for the seeded exercise
-- catalog. Keyed by slug (ids are random UUIDs) and idempotent via ON CONFLICT, so
-- it is safe to re-run and safe on any DB that already ran the catalog seeds. The
-- English "exercises"."name" stays the canonical fallback for untranslated locales.
INSERT INTO "exercise_translations" ("exercise_id", "locale", "name")
SELECT e."id", 'es', v."name"
FROM "exercises" e
JOIN (VALUES
	('45-degree-hip-extension', 'Extensión de Cadera a 45°'),
	('ab-wheel-rollout', 'Rueda Abdominal'),
	('anderson-squat', 'Sentadilla Anderson'),
	('arnold-press', 'Press Arnold'),
	('assisted-chin-up', 'Dominada Supina Asistida (Máquina)'),
	('assisted-dip', 'Fondo Asistido (Máquina)'),
	('assisted-pull-up', 'Dominada Asistida (Máquina)'),
	('back-extension', 'Extensión de Espalda'),
	('back-squat', 'Sentadilla Trasera'),
	('barbell-curl', 'Curl con Barra'),
	('barbell-front-raise', 'Elevación Frontal con Barra'),
	('barbell-hack-squat', 'Hack Squat con Barra'),
	('barbell-hip-thrust', 'Hip Thrust con Barra'),
	('barbell-lunge', 'Zancada con Barra'),
	('barbell-row', 'Remo con Barra'),
	('barbell-shrug', 'Encogimiento con Barra'),
	('bayesian-cable-curl', 'Curl Bayesiano en Polea'),
	('behind-the-neck-press', 'Press Tras Nuca'),
	('behind-the-neck-pulldown', 'Jalón Tras Nuca'),
	('belt-squat', 'Sentadilla con Cinturón'),
	('bench-dip', 'Fondo en Banco'),
	('bench-press', 'Press de Banca con Barra'),
	('block-pull', 'Peso Muerto con Bloques'),
	('board-press', 'Board Press'),
	('box-squat', 'Sentadilla al Cajón'),
	('b-stance-hip-thrust', 'Hip Thrust en Postura B'),
	('b-stance-rdl', 'Peso Muerto Rumano en Postura B'),
	('bulgarian-split-squat', 'Sentadilla Búlgara'),
	('cable-crossover-curl', 'Curl Cruzado en Polea'),
	('cable-crossover-triceps-extension', 'Extensión de Tríceps Cruzada en Polea'),
	('cable-crunch', 'Crunch en Polea'),
	('cable-curl', 'Curl en Polea'),
	('cable-fly', 'Aperturas en Polea'),
	('cable-front-raise', 'Elevación Frontal en Polea'),
	('cable-glute-kickback', 'Patada de Glúteo en Polea'),
	('cable-hammer-curl', 'Curl Martillo en Polea'),
	('cable-hip-abduction', 'Abducción de Cadera en Polea'),
	('cable-hip-adduction', 'Aducción de Cadera en Polea'),
	('cable-lateral-raise', 'Elevación Lateral en Polea'),
	('cable-overhead-triceps-extension', 'Extensión de Tríceps sobre la Cabeza en Polea'),
	('cable-pullover', 'Pullover en Polea'),
	('cable-pull-through', 'Pull-Through en Polea'),
	('cable-rear-delt-fly', 'Aperturas Posteriores en Polea'),
	('cable-rope-curl', 'Curl con Cuerda en Polea'),
	('cable-rope-row', 'Remo con Cuerda en Polea'),
	('cable-shrug', 'Encogimiento en Polea'),
	('cable-triceps-kickback', 'Patada de Tríceps en Polea'),
	('cable-upright-row', 'Remo al Mentón en Polea'),
	('cable-y-raise', 'Elevación en Y en Polea'),
	('chest-supported-dumbbell-row', 'Remo con Mancuernas con Apoyo en el Pecho'),
	('chest-supported-row', 'Remo con Apoyo en el Pecho'),
	('chin-up', 'Dominada Supina'),
	('close-grip-barbell-curl', 'Curl con Barra Agarre Cerrado'),
	('close-grip-bench-press', 'Press de Banca Agarre Cerrado'),
	('close-grip-cable-row', 'Remo en Polea Agarre Cerrado'),
	('close-grip-lat-pulldown', 'Jalón al Pecho Agarre Cerrado'),
	('close-grip-pull-up', 'Dominada Agarre Cerrado'),
	('close-grip-push-up', 'Flexión Agarre Cerrado'),
	('concentration-curl', 'Curl de Concentración'),
	('conventional-deadlift', 'Peso Muerto Convencional'),
	('copenhagen-plank', 'Plancha Copenhague'),
	('cossack-squat', 'Sentadilla Cosaca'),
	('cross-body-hammer-curl', 'Curl Martillo Cruzado'),
	('crunch', 'Crunch'),
	('curtsy-lunge', 'Zancada en Reverencia'),
	('dead-bug', 'Dead Bug'),
	('decline-bench-press', 'Press de Banca Declinado con Barra'),
	('decline-dumbbell-press', 'Press Declinado con Mancuernas'),
	('deep-front-squat', 'Sentadilla Frontal Profunda'),
	('deficit-deadlift', 'Peso Muerto con Déficit'),
	('deficit-reverse-lunge', 'Zancada Inversa con Déficit'),
	('dip', 'Fondo'),
	('donkey-calf-raise', 'Elevación de Gemelos Donkey'),
	('donkey-kick', 'Patada de Glúteo (Donkey Kick)'),
	('drag-curl', 'Curl de Arrastre (Drag Curl)'),
	('dumbbell-bench-press', 'Press de Banca con Mancuernas'),
	('dumbbell-curl', 'Curl con Mancuernas'),
	('dumbbell-floor-press', 'Press en el Suelo con Mancuernas'),
	('dumbbell-fly', 'Aperturas con Mancuernas'),
	('dumbbell-hip-thrust', 'Hip Thrust con Mancuerna'),
	('dumbbell-preacher-curl', 'Curl Predicador con Mancuerna'),
	('dumbbell-pullover', 'Pullover con Mancuerna'),
	('dumbbell-row', 'Remo con Mancuerna'),
	('dumbbell-shoulder-press', 'Press de Hombros con Mancuernas de Pie'),
	('dumbbell-shrug', 'Encogimiento con Mancuernas'),
	('dumbbell-skullcrusher', 'Press Francés con Mancuernas'),
	('dumbbell-triceps-kickback', 'Patada de Tríceps con Mancuerna'),
	('dumbbell-upright-row', 'Remo al Mentón con Mancuernas'),
	('ez-bar-curl', 'Curl con Barra Z'),
	('ez-bar-skullcrusher', 'Press Francés con Barra Z'),
	('face-pull', 'Face Pull'),
	('floor-press', 'Press en el Suelo'),
	('frog-pump', 'Frog Pump'),
	('front-raise', 'Elevación Frontal'),
	('front-squat', 'Sentadilla Frontal'),
	('glute-bridge', 'Puente de Glúteos'),
	('glute-ham-raise', 'Elevación Glúteo-Femoral (GHR)'),
	('goblet-squat', 'Sentadilla Goblet'),
	('good-morning', 'Good Morning'),
	('hack-squat', 'Hack Squat'),
	('hammer-curl', 'Curl Martillo'),
	('hammer-strength-row', 'Remo en Máquina Hammer Strength'),
	('hanging-leg-raise', 'Elevación de Piernas Colgado'),
	('high-bar-squat', 'Sentadilla Barra Alta'),
	('high-cable-curl', 'Curl en Polea Alta'),
	('high-cable-row', 'Remo en Polea Alta'),
	('hip-abduction', 'Abducción de Cadera en Máquina'),
	('hip-adduction', 'Aducción de Cadera en Máquina'),
	('hip-extension-machine', 'Extensión de Cadera en Máquina'),
	('horizontal-leg-press', 'Prensa de Piernas Horizontal'),
	('incline-bench-press', 'Press de Banca Inclinado con Barra'),
	('incline-cable-fly', 'Aperturas Inclinadas en Polea'),
	('incline-dumbbell-curl', 'Curl Inclinado con Mancuernas'),
	('incline-dumbbell-press', 'Press Inclinado con Mancuernas'),
	('incline-hammer-curl', 'Curl Martillo Inclinado'),
	('incline-skullcrusher', 'Press Francés Inclinado'),
	('inverted-row', 'Remo Invertido'),
	('iso-lateral-pulldown', 'Jalón en Máquina Iso-Lateral'),
	('iso-lateral-row', 'Remo en Máquina Iso-Lateral'),
	('jm-press', 'Press JM'),
	('kas-glute-bridge', 'Puente de Glúteos KAS'),
	('kneeling-cable-pulldown', 'Jalón en Polea de Rodillas'),
	('kroc-row', 'Remo Kroc'),
	('landmine-press', 'Press Landmine'),
	('landmine-row', 'Remo Landmine'),
	('landmine-squat', 'Sentadilla Landmine'),
	('larsen-press', 'Larsen Press'),
	('lateral-lunge', 'Zancada Lateral'),
	('lateral-raise', 'Elevación Lateral'),
	('lat-pulldown', 'Jalón al Pecho'),
	('leaning-cable-lateral-raise', 'Elevación Lateral Inclinada en Polea'),
	('leg-extension', 'Extensión de Cuádriceps'),
	('leg-press', 'Prensa de Piernas'),
	('leg-press-calf-raise', 'Elevación de Gemelos en Prensa'),
	('low-bar-squat', 'Sentadilla Barra Baja'),
	('lying-leg-curl', 'Curl Femoral Tumbado'),
	('lying-leg-raise', 'Elevación de Piernas Tumbado'),
	('machine-back-extension', 'Extensión de Espalda en Máquina'),
	('machine-chest-press', 'Press de Pecho en Máquina'),
	('machine-curl', 'Curl en Máquina'),
	('machine-glute-kickback', 'Patada de Glúteo en Máquina'),
	('machine-hip-thrust', 'Hip Thrust en Máquina'),
	('machine-independent-curl', 'Curl en Máquina Independiente'),
	('machine-lateral-raise', 'Elevación Lateral en Máquina'),
	('machine-lat-pulldown', 'Jalón al Pecho en Máquina'),
	('machine-preacher-curl', 'Curl Predicador en Máquina'),
	('machine-pullover', 'Pullover en Máquina'),
	('machine-rear-delt-row', 'Remo Posterior en Máquina'),
	('machine-row', 'Remo en Máquina'),
	('machine-shoulder-press', 'Press de Hombros en Máquina'),
	('machine-shrug', 'Encogimiento en Máquina'),
	('machine-triceps-dip', 'Fondo de Tríceps en Máquina'),
	('machine-triceps-extension', 'Extensión de Tríceps en Máquina'),
	('meadows-row', 'Remo Meadows'),
	('neutral-grip-lat-pulldown', 'Jalón al Pecho Agarre Neutro'),
	('neutral-grip-pull-up', 'Dominada Agarre Neutro'),
	('nordic-curl', 'Curl Nórdico de Isquios'),
	('overhead-press', 'Press Militar'),
	('overhead-triceps-extension', 'Extensión de Tríceps sobre la Cabeza'),
	('pallof-press', 'Press Pallof'),
	('pause-bench-press', 'Press de Banca con Pausa'),
	('paused-deadlift', 'Peso Muerto con Pausa'),
	('pause-front-squat', 'Sentadilla Frontal con Pausa'),
	('pause-squat', 'Sentadilla con Pausa'),
	('pec-deck', 'Contractor de Pecho (Pec Deck)'),
	('pendlay-row', 'Remo Pendlay'),
	('pendulum-squat', 'Sentadilla Pendular'),
	('pike-push-up', 'Flexión Pike'),
	('pin-press', 'Pin Press'),
	('pin-squat', 'Sentadilla con Pines'),
	('plank', 'Plancha'),
	('plie-squat', 'Sentadilla Plié'),
	('preacher-curl', 'Curl Predicador (Banco Scott)'),
	('pull-up', 'Dominada'),
	('push-press', 'Push Press'),
	('push-up', 'Flexión'),
	('quadruped-hip-extension', 'Extensión de Cadera en Cuadrupedia'),
	('rack-pull', 'Rack Pull'),
	('rear-delt-fly', 'Aperturas Posteriores'),
	('reverse-curl', 'Curl Inverso'),
	('reverse-grip-cable-row', 'Remo en Polea Agarre Supino'),
	('reverse-grip-lat-pulldown', 'Jalón al Pecho Agarre Supino'),
	('reverse-grip-pushdown', 'Extensión de Tríceps Agarre Supino'),
	('reverse-hack-squat', 'Hack Squat Inverso'),
	('reverse-hyperextension', 'Hiperextensión Inversa'),
	('reverse-lunge', 'Zancada Inversa'),
	('reverse-pec-deck', 'Contractor Posterior (Pec Deck Inverso)'),
	('romanian-deadlift', 'Peso Muerto Rumano'),
	('rope-pushdown', 'Extensión de Tríceps con Cuerda'),
	('russian-twist', 'Giro Ruso'),
	('safety-bar-squat', 'Sentadilla con Barra Safety'),
	('seal-row', 'Remo Seal'),
	('seated-barbell-overhead-triceps-extension', 'Extensión de Tríceps sobre la Cabeza con Barra Sentado'),
	('seated-cable-row', 'Remo Sentado en Polea'),
	('seated-calf-raise', 'Elevación de Gemelos Sentado'),
	('seated-dumbbell-curl', 'Curl con Mancuernas Sentado'),
	('seated-dumbbell-press', 'Press de Hombros con Mancuernas Sentado'),
	('seated-lateral-raise', 'Elevación Lateral con Mancuernas Sentado'),
	('seated-leg-curl', 'Curl Femoral Sentado'),
	('seated-machine-high-row', 'Remo Alto en Máquina Sentado'),
	('seated-overhead-press', 'Press Militar Sentado'),
	('seated-single-leg-curl', 'Curl Femoral Sentado a Una Pierna'),
	('side-plank', 'Plancha Lateral'),
	('single-arm-cable-curl', 'Curl en Polea a Una Mano'),
	('single-arm-cable-kickback', 'Patada de Tríceps en Polea a Una Mano'),
	('single-arm-cable-lateral-raise', 'Elevación Lateral en Polea a Una Mano'),
	('single-arm-cable-overhead-triceps-extension', 'Extensión de Tríceps sobre la Cabeza en Polea a Una Mano'),
	('single-arm-cable-pushdown', 'Extensión de Tríceps en Polea a Una Mano'),
	('single-arm-cable-rear-delt-fly', 'Apertura Posterior en Polea a Una Mano'),
	('single-arm-cable-row', 'Remo en Polea a Una Mano'),
	('single-arm-dumbbell-press', 'Press con Mancuerna a Una Mano'),
	('single-arm-landmine-press', 'Press Landmine a Una Mano'),
	('single-arm-lat-pulldown', 'Jalón al Pecho en Polea a Una Mano'),
	('single-arm-machine-triceps-extension', 'Extensión de Tríceps en Máquina a Una Mano'),
	('single-arm-overhead-triceps-extension', 'Extensión de Tríceps sobre la Cabeza con Mancuerna a Una Mano'),
	('single-arm-preacher-curl', 'Curl Predicador a Una Mano'),
	('single-leg-calf-raise', 'Elevación de Gemelos a Una Pierna'),
	('single-leg-extension', 'Extensión de Cuádriceps a Una Pierna'),
	('single-leg-hip-thrust', 'Hip Thrust a Una Pierna'),
	('single-leg-lying-curl', 'Curl Femoral Tumbado a Una Pierna'),
	('single-leg-press', 'Prensa de Piernas a Una Pierna'),
	('single-leg-rdl', 'Peso Muerto Rumano a Una Pierna'),
	('sissy-squat', 'Sentadilla Sissy'),
	('sit-up', 'Abdominal Completo (Sit-Up)'),
	('skullcrusher', 'Press Francés'),
	('slider-leg-curl', 'Curl Femoral con Deslizadores'),
	('smith-machine-bench-press', 'Press de Banca en Máquina Smith'),
	('smith-machine-calf-raise', 'Elevación de Gemelos en Máquina Smith'),
	('smith-machine-hip-thrust', 'Hip Thrust en Máquina Smith'),
	('smith-machine-lunge', 'Zancada en Máquina Smith'),
	('smith-machine-row', 'Remo en Máquina Smith'),
	('smith-machine-shoulder-press', 'Press de Hombros en Máquina Smith'),
	('smith-machine-squat', 'Sentadilla en Máquina Smith'),
	('snatch-grip-deadlift', 'Peso Muerto Agarre de Arrancada'),
	('spider-curl', 'Curl Araña (Spider)'),
	('split-squat', 'Zancada Estática'),
	('spoto-press', 'Spoto Press'),
	('stability-ball-leg-curl', 'Curl Femoral con Fitball'),
	('standing-cable-row', 'Remo en Polea de Pie'),
	('standing-calf-raise', 'Elevación de Gemelos de Pie'),
	('standing-leg-curl', 'Curl Femoral de Pie'),
	('standing-single-leg-curl', 'Curl Femoral de Pie a Una Pierna'),
	('step-up', 'Subida al Cajón'),
	('stiff-leg-deadlift', 'Peso Muerto Piernas Rígidas'),
	('straight-arm-pulldown', 'Jalón con Brazos Rectos'),
	('straight-bar-pushdown', 'Extensión de Tríceps con Barra'),
	('sumo-deadlift', 'Peso Muerto Sumo'),
	('sumo-squat', 'Sentadilla Sumo'),
	('tate-press', 'Press Tate'),
	('t-bar-row', 'Remo en T'),
	('tempo-bench-press', 'Press de Banca a Tempo'),
	('tempo-squat', 'Sentadilla a Tempo'),
	('tibialis-raise', 'Elevación de Tibial'),
	('trap-bar-deadlift', 'Peso Muerto con Barra Hexagonal'),
	('trap-bar-shrug', 'Encogimiento con Barra Hexagonal'),
	('triceps-dip', 'Fondo de Tríceps'),
	('triceps-pushdown', 'Extensión de Tríceps en Polea'),
	('upright-row', 'Remo al Mentón'),
	('v-bar-lat-pulldown', 'Jalón al Pecho con Triángulo (V)'),
	('v-bar-pushdown', 'Extensión de Tríceps con Barra V'),
	('vertical-leg-press', 'Prensa de Piernas Vertical'),
	('v-squat', 'Sentadilla en V'),
	('waiter-curl', 'Curl Camarero'),
	('walking-lunge', 'Zancada Caminando'),
	('weighted-pull-up', 'Dominada Lastrada'),
	('wide-grip-barbell-curl', 'Curl con Barra Agarre Ancho'),
	('wide-grip-bench-press', 'Press de Banca Agarre Ancho'),
	('wide-grip-lat-pulldown', 'Jalón al Pecho Agarre Ancho'),
	('wide-grip-pull-up', 'Dominada Agarre Ancho'),
	('wide-grip-seated-cable-row', 'Remo Sentado en Polea Agarre Ancho'),
	('yates-row', 'Remo Yates (Agarre Supino)'),
	('zercher-squat', 'Sentadilla Zercher'),
	('zottman-curl', 'Curl Zottman'),
	('z-press', 'Z Press')
) AS v("slug", "name") ON e."slug" = v."slug"
ON CONFLICT ("exercise_id", "locale") DO UPDATE SET "name" = EXCLUDED."name";
