version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: powerlog-dev-backend
    ports:
      - 3001:3001

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: powerlog-dev-frontend
    ports:
      - 3000:3000