import { describe, expect, it } from 'vitest'

import {
    FakeAuthConfig,
    FakeAuthMetrics,
    FakeClock,
    FakeIdGenerator,
    FakeRefreshTokenGenerator,
    FakeTokenSigner,
    InMemoryRefreshTokenRepository,
    InMemoryUserRepository,
} from '../../../../../../tests/doubles/auth'
import { FakeProfiles, fakeEventPublisher, RecordingEventBus } from '../../../../../../tests/doubles/shared'
import { UserMother } from '../../../../../../tests/mothers/auth'
import { GoogleIdentityLinkedIntegrationEvent } from '../../../../../shared/integration-events/google-identity-linked.integration-event'
import { UserRegisteredIntegrationEvent } from '../../../../../shared/integration-events/user-registered.integration-event'
import { SessionIssuer } from '../../services/session-issuer.service'
import { LoginWithGoogleCommand } from './login-with-google.command'
import { LoginWithGoogleHandler } from './login-with-google.handler'

const NOW = new Date('2026-01-01T00:00:00.000Z')

function setup(seed: ReturnType<UserMother['buildExisting']>[] = [], ids: string[] = ['new-user', 'family-1']) {
    const users = new InMemoryUserRepository(seed)
    const refreshTokens = new InMemoryRefreshTokenRepository()
    const signer = new FakeTokenSigner()
    const idGen = new FakeIdGenerator(ids)
    // Profile boundary: existing users get a seeded snapshot; new sign-ups get one
    // populated by provisioning (handle derived from the email).
    const profiles = new FakeProfiles()
    for (const u of seed) profiles.set(u.id, { username: 'gymrat', avatarUrl: null })
    const sessions = new SessionIssuer(
        signer,
        new FakeRefreshTokenGenerator(),
        refreshTokens,
        new FakeClock(NOW),
        new FakeAuthConfig(),
        idGen,
        profiles,
    )
    const eventBus = new RecordingEventBus()
    const metrics = new FakeAuthMetrics()
    const handler = new LoginWithGoogleHandler(
        users,
        idGen,
        new FakeClock(NOW),
        sessions,
        profiles,
        fakeEventPublisher(),
        eventBus.asEventBus(),
        metrics,
    )
    return { handler, users, refreshTokens, signer, eventBus, profiles, metrics }
}

describe('LoginWithGoogleHandler', () => {
    it('creates a passwordless athlete with the Google identity when none exists', async () => {
        const ctx = setup()

        const result = await ctx.handler.execute(
            new LoginWithGoogleCommand('g-1', 'New@Example.com', 'New Lifter', 'New', 'Lifter', 'https://pic'),
        )

        const saved = ctx.users.all()
        expect(saved).toHaveLength(1)
        expect(saved[0]?.email.value).toBe('new@example.com')
        // Handle autogenerated (in the profile) from the email local-part → JWT.
        expect((await ctx.signer.verifyAccessToken(result.accessToken)).username).toBe('new')
        expect(ctx.profiles.calls[0]).toMatchObject({ userId: 'new-user', email: 'new@example.com' })
        expect(saved[0]?.hasPassword()).toBe(false)
        expect(saved[0]?.hasIdentity('google', 'g-1')).toBe(true)
        expect(saved[0]?.role.value).toBe('athlete')
        expect(result.userId).toBe('new-user')

        const event = ctx.eventBus.firstOf(UserRegisteredIntegrationEvent)
        expect(event?.source).toBe('google')
        expect(event?.google).toEqual({
            displayName: 'New Lifter',
            firstName: 'New',
            lastName: 'Lifter',
            pictureUrl: 'https://pic',
        })
    })

    it('never persists the raw refresh token', async () => {
        const ctx = setup()

        const result = await ctx.handler.execute(new LoginWithGoogleCommand('g-1', 'new@example.com'))

        const stored = ctx.refreshTokens.all()
        expect(stored).toHaveLength(1)
        expect(stored[0]?.tokenHash).not.toBe(result.refreshToken)
    })

    it('reuses the account already linked to that Google identity', async () => {
        const existing = UserMother.coach()
            .asAdmin()
            .withId('u-existing')
            .withEmail('coach@example.com')
            .withoutPassword()
            .withGoogleIdentity('g-1')
            .buildExisting()
        const ctx = setup([existing], ['family-1'])

        const result = await ctx.handler.execute(new LoginWithGoogleCommand('g-1', 'coach@example.com'))

        expect(ctx.users.all()).toHaveLength(1)
        expect(result.userId).toBe('u-existing')
        expect(await ctx.signer.verifyAccessToken(result.accessToken)).toEqual({
            userId: 'u-existing',
            email: 'coach@example.com',
            username: 'gymrat',
            role: 'coach',
            isAdmin: true,
            avatar: null,
        })
        expect(ctx.metrics.logins).toEqual([{ method: 'google', outcome: 'success' }])
    })

    it('auto-links the Google identity to an existing same-email account', async () => {
        const existing = UserMother.create().withId('u-existing').withEmail('known@example.com').buildExisting()
        const ctx = setup([existing], ['family-1'])

        const result = await ctx.handler.execute(
            new LoginWithGoogleCommand('g-2', 'known@example.com', 'Known User', 'Known', 'User'),
        )

        expect(ctx.users.all()).toHaveLength(1)
        expect(result.userId).toBe('u-existing')
        expect(ctx.users.all()[0]?.hasIdentity('google', 'g-2')).toBe(true)

        const event = ctx.eventBus.firstOf(GoogleIdentityLinkedIntegrationEvent)
        expect(event?.userId).toBe('u-existing')
        expect(event?.google.firstName).toBe('Known')
    })
})
